spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_platform
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#jwt:
#  secret: mySuperSecretKey1234567890

# src/main/resources/application.yml
jwt:
  secret: YourSuperSecretKey123!
  expiration: 3600000  # optional

